name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=annotatorx --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Validate example annotations
      run: |
        python -m annotatorx validate annotations/example_annotations.json
    
    - name: Test annotation pipeline
      run: |
        python -m annotatorx annotate example_dataset --seed 0 --output annotations/test_output.json
        python -m annotatorx validate annotations/test_output.json
        python -m annotatorx stats annotations/test_output.json

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t annotatorx:test .
    
    - name: Test Docker container
      run: |
        docker run --rm annotatorx:test python -m annotatorx --help
        docker run --rm annotatorx:test python -m pytest tests/ -v
    
    - name: Test docker-compose
      run: |
        docker-compose run --rm test
        docker-compose run --rm validate
